name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Check directory structure
      run: |
        echo "项目目录结构："
        ls -la
        echo "damai_ticket目录："
        ls -la damai_ticket || echo "目录不存在"
        echo "assets目录："
        ls -la assets || echo "目录不存在"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
        pip install pillow
        pip install requests
        pip install pyyaml

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          build-essential \
          libsqlite3-dev \
          sqlite3 \
          bzip2 \
          libbz2-dev \
          zlib1g-dev \
          libssl-dev \
          openssl \
          libgdbm-dev \
          libgdbm-compat-dev \
          liblzma-dev \
          libreadline-dev \
          libncursesw5-dev \
          libffi-dev \
          uuid-dev \
          libopenblas-dev \
          libjpeg-dev \
          libtiff-dev \
          libfreetype6-dev \
          libwebp-dev \
          autoconf \
          automake \
          cmake \
          gettext \
          patch \
          pkg-config

    - name: Create any missing directories
      run: |
        mkdir -p assets
        mkdir -p damai_ticket
        python create_assets.py || echo "Failed to create assets, but continuing..."

    - name: Check buildozer.spec
      run: |
        echo "Buildozer.spec内容："
        cat buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Check build logs
      if: always()
      run: |
        echo "构建日志："
        cat .buildozer/logs/buildozer-*.log || echo "No buildozer logs found"

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: bin/*.apk

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: .buildozer/logs/ 